# Generated by Django 6.1.1 on 2026-09-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.CharField(default='No description available', max_length=500),
        ),
    ]
