# Generated by Django 6.1.1 on 2026-09-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
